### ISSUE TITLE
Crash - com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.onScrollStateChanged

### ISSUE THREAD

**Issue by vinaywadhwa** [lsjwzh/RecyclerViewPager#100]
Here's a crash i am receiving in one of my apps. I can't tell how it's happening exactly but it seems to be coming from onScrollStateChanged . Could you guide me to a solution/workaround? TIA

Here's the complete stack trace 

0	java.lang.NullPointerException
1	at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.onScrollStateChanged(SourceFile:469)
2	at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(SourceFile:3964)
3	at android.support.v7.widget.RecyclerView.setScrollState(SourceFile:1194)
4	at android.support.v7.widget.RecyclerView.onTouchEvent(SourceFile:2483)
5	at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.onTouchEvent(SourceFile:405)
6	at android.view.View.dispatchTouchEvent(View.java:8177)
7	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2429)
8	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
9	at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.dispatchTouchEvent(SourceFile:391)
10	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
11	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
12	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
13	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
14	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
15	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
16	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
17	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
18	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
19	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
20	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
21	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
22	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
23	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
24	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
25	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
26	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
27	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
28	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435)
29	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2168)
30	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2309)
31	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1628)
32	at android.app.Activity.dispatchTouchEvent(Activity.java:2580)
33	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
34	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:60)
35	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2257)
36	at android.view.View.dispatchPointerEvent(View.java:8391)
37	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4848)
38	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4712)
39	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4270)
40	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4324)
41	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4293)
42	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4404)
43	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4301)
44	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4461)
45	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4270)
46	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4324)
47	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4293)
48	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4301)
49	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4270)
50	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6653)
51	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6566)
52	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6537)
53	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6502)
54	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6733)
55	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
56	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
57	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
58	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6706)
59	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6752)
60	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:812)
61	at android.view.Choreographer.doCallbacks(Choreographer.java:612)
62	at android.view.Choreographer.doFrame(Choreographer.java:580)
63	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:798)
64	at android.os.Handler.handleCallback(Handler.java:733)
65	at android.os.Handler.dispatchMessage(Handler.java:95)
66	at android.os.Looper.loop(Looper.java:146)
67	at android.app.ActivityThread.main(ActivityThread.java:5641)
68	at java.lang.reflect.Method.invokeNative(Native Method)
69	at java.lang.reflect.Method.invoke(Method.java:515)
70	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1288)
71	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1104)
72	at dalvik.system.NativeStart.main(Native Method)

**Comment by samvanderhyden** [comment]
this is affecting an app I have in production as well. would love a release with this fix soon.
