### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by petar19992** [lsjwzh/RecyclerViewPager#104]
Hello,
I am using your component in my project and sometimes the application will crash when I am exiting the application by clicking the system home button. This bug is not happening always, but only sometimes. Please find attached the log of the problem.

`{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 06-17 09:27:34.977 9635-9635/? A/onPause: usao u pause\
06-17 09:27:35.177 9635-9635/? E/AndroidRuntime: FATAL EXCEPTION: main\
                                                 Process: com.myApp, PID: 9635\
                                                 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder\{3115d7ae position=2 id=-1, oldPos=-1, pLpos:-1 no parent\}\
                                                     at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:4247)\
                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4378)\
                                                     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4359)\
                                                     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)\
                                                     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)\
                                                     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)\
                                                     at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)\
                                                     at android.support.v7.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1006)\
                                                     at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3803)\
                                                     at android.os.Handler.handleCallback(Handler.java:739)\
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)\
                                                     at android.os.Looper.loop(Looper.java:135)\
                                                     at android.app.ActivityThread.main(ActivityThread.java:5910)\
                                                     at java.lang.reflect.Method.invoke(Native Method)\
                                                     at java.lang.reflect.Method.invoke(Method.java:372)\
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)\
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)}`

**Comment by lsjwzh** [comment]
Thx, I will check it A.S.A.P

**Comment by petar19992** [comment]
I noticed why and when this problem occurs. I would call your function "smoothScrollToPosition" in my activity with the help of the Handler and its "postDelay" function. It is possible that the execution of your function "smoothScrollToPosition" had not yet finished, and I tried to close my activity.

**Comment by tamtom** [comment]
how did you solve it @petar19992
