### ISSUE TITLE
Fatal Exception: java.lang.ArithmeticException divide by zero

### ISSUE THREAD

**Issue by bhnverma123** [lsjwzh/RecyclerViewPager#145]
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.lsjwzh.widget.recyclerviewpager.LoopRecyclerViewPagerAdapter.getActualPosition(LoopRecyclerViewPagerAdapter.java:52)
       at com.lsjwzh.widget.recyclerviewpager.LoopRecyclerViewPagerAdapter.getItemViewType(LoopRecyclerViewPagerAdapter.java:33)
       at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5430)
       at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:270)
       at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:324)
       at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:337)
       at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:344)
       at android.support.v7.widget.GapWorker.run(GapWorker.java:370)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by bhnverma123** [comment]
Please do something
