### ISSUE TITLE
not compatible with Smart-Adapter library ?

### ISSUE THREAD

**Issue by DJafari** [lsjwzh/RecyclerViewPager#19]
https://github.com/mrmans0n/smart-adapters

Item

```java
public class Item {
    public String number;

    public Item(String number) {
        this.number = number;
    }
}
```

ItemView
```java
public class ItemView extends BindableLayout<Item> {
    @InjectView(R.id.text) public TextView text;

    public ItemView(Context context) {
        super(context);
    }

    @Override
    public int getLayoutId() {
        return R.layout.item_layout;
    }

    @Override
    public void onViewInflated() {
        ButterKnife.inject(this);
    }

    @Override
    public void bind(Item item) {
        this.text.setText(item.number);
    }
}
```

```java
RecyclerMultiAdapter adapter = SmartAdapter.empty().map(Item.class, ItemView.class).into(this.mRecyclerView);
        for(int i = 0; i < 30; i++) {
            adapter.addItem(new Item("" + i));
        }

        LinearLayoutManager layout = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);
        mRecyclerView.setLayoutManager(layout);
        mRecyclerView.setHasFixedSize(true);
        mRecyclerView.setAdapter(adapter);
```

Error Exception on launch :
```
Caused by: java.lang.IllegalStateException: Cannot change whether this adapter has stable IDs while the adapter has registered observers.
            at android.support.v7.widget.RecyclerView$Adapter.setHasStableIds(RecyclerView.java:5114)
            at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPagerAdapter.setHasStableIds(RecyclerViewPagerAdapter.java:57)
            at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPagerAdapter.<init>(RecyclerViewPagerAdapter.java:22)
            at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.setAdapter(RecyclerViewPager.java:108)
            at ir.fadesign.myapplication.MainActivity.onCreate(MainActivity.java:40)
```

**Comment by lsjwzh** [comment]
It looks like a bug. I will handle it.

**Comment by lsjwzh** [comment]
It is not a bug. 
Your adapter 'RecyclerMultiAdapter' has been setted into an RecyclerView twice.
You can try this :+1: 
        LinearLayoutManager layout = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);
        mRecyclerView.setLayoutManager(layout);
        mRecyclerView.setHasFixedSize(true);

RecyclerMultiAdapter adapter = SmartAdapter.empty().map(Item.class, ItemView.class).into(this.mRecyclerView);
        for(int i = 0; i < 30; i++) {
            adapter.addItem(new Item("" + i));
        }

https://github.com/mrmans0n/smart-adapters/blob/master/library/src/main/java/io/nlopez/smartadapters/SmartAdapter.java

**Comment by DJafari** [comment]
i tested your solution, but again return new exception

```java
 java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
            at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPagerAdapter.onBindViewHolder(RecyclerViewPagerAdapter.java:48)
            at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5084)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4385)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1947)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1359)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1322)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
            at android.view.View.layout(View.java:15671)
```

**Comment by lsjwzh** [comment]
This is actually a bug. I try to fix it in latest commit.Could you test it again?

**Comment by DJafari** [comment]
yes, please fix and let me to test

**Comment by lsjwzh** [comment]
https://github.com/lsjwzh/RecyclerViewPager/commit/31fda3b2cf263c47883e054800bbfd73963fa8c3

**Comment by DJafari** [comment]
working now ! thaaanks

please push it to maven

**Comment by lsjwzh** [comment]
done！
