### ISSUE TITLE
Resources$NotFoundException 

### ISSUE THREAD

**Issue by Robertoq7** [lsjwzh/RecyclerViewPager#23]
Hi,

I set the pager as in the demo, but I got this exception:
android.content.res.Resources$NotFoundException: Unable to find resource ID #0xd7282e18
            at android.content.res.Resources.getResourceName(Resources.java:3357)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
            at com.lsjwzh.widget.recyclerviewpager.FragmentStatePagerAdapter$FragmentViewHolder.onViewAttachedToWindow(FragmentStatePagerAdapter.java:147)

v1.0.5

Thanks,
Robert

**Comment by lsjwzh** [comment]
I have resolve this in 1.0.6, it will be release to maven tomorrow.
