### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid target position

### ISSUE THREAD

**Issue by comkongandroid** [lsjwzh/RecyclerViewPager#61]
when no network have this ,the oldpostion -1 new position 0 

Exception dispatching input event.
02-16 08:46:38.551 31953-31953/com.noglon.kk.com E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI: java.lang.IllegalArgumentException: Invalid target position
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.support.v7.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:8859)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.support.v7.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:6122)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.support.v7.widget.LinearLayoutManager.smoothScrollToPosition(LinearLayoutManager.java:433)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.support.v7.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1377)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at com.damai.dmlive.support.widget.RecyclerViewPager.smoothScrollToPosition(RecyclerViewPager.java:179)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at com.damai.dmlive.support.widget.RecyclerViewPager.onScrollStateChanged(RecyclerViewPager.java:424)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:3732)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1182)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2438)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at com.damai.dmlive.support.widget.RecyclerViewPager.onTouchEvent(RecyclerViewPager.java:360)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.View.dispatchTouchEvent(View.java:9148)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2680)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2351)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at com.damai.dmlive.support.widget.RecyclerViewPager.dispatchTouchEvent(RecyclerViewPager.java:346)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2747)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1840)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.app.Activity.dispatchTouchEvent(Activity.java:3027)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2708)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.View.dispatchPointerEvent(View.java:9358)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5044)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4874)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4482)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4539)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6940)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6813)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6784)
02-16 08:46:38.561 31953-31953/com.noglon.kk.com E/MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:70

**Comment by grosalex** [comment]
Hi there I got the same problem did you find a solution?

Regards,

**Comment by DanielyBotelho** [comment]
Same here

**Comment by miannoumanshah** [comment]
i have the same issue did this issue is resolved ?

**Comment by ababavali23** [comment]
hi for me also app crashes when there is no elements in recyclerview.
