### ISSUE TITLE
Cannot change whether this adapter has stable IDs while the adapter has registered observers.

### ISSUE THREAD

**Issue by MrVilkaman** [lsjwzh/RecyclerViewPager#83]
I used next code in my fragment
```
if (adapter == null) {
	adapter = new TargetAdapter();
	getPresenter().loadTarget();
}
viewPager.setAdapter(adapter);
```
When I open new fragment and returned back i got exception in last line:
```
 java.lang.IllegalStateException: Cannot change whether this adapter has stable IDs while the adapter has registered observers.
                      at android.support.v7.widget.RecyclerView$Adapter.setHasStableIds(RecyclerView.java:5535)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPagerAdapter.setHasStableIds(RecyclerViewPagerAdapter.java:57)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPagerAdapter.<init>(RecyclerViewPagerAdapter.java:21)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.ensureRecyclerViewPagerAdapter(RecyclerViewPager.java:495)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.setAdapter(RecyclerViewPager.java:123)
                      at ...targetlist.TargetlistScreenFragment.setupRecyclerView(TargetlistScreenFragment.java:61)
```
When I used normal RecyclerView my code works well!

**Comment by justincpollard** [comment]
I encountered the same problem yesterday. While this may be a bug in the library, why do you need to set the adapter again? I assume the `setAdapter()` call in is `onResume` ... why not in `onCreate`?

**Comment by MrVilkaman** [comment]
@justincpollard I do it in `onCreateView`. When I was come back from another fragment, I have new instance of `RecyclerViewPager` but old instance of adapter

**Comment by justincpollard** [comment]
Aw, I see. Well you could just create a new adapter to back the new RecyclerViewPager, right? If you're loading something from network maybe you could do that in onCreate, then simply set those items on the new adapter in onCreateView?

**Comment by MrVilkaman** [comment]
@justincpollard  I can do so, but my approach is  works in the usual RecyclerView.

**Comment by lsjwzh** [comment]
I will check it ~~~ Thx for your issue!

**Comment by whaleswallace** [comment]
I'm experiencing the same issue, any luck ?

java.lang.IllegalStateException: Cannot change whether this adapter has stable IDs while the adapter has registered observers.
                      at android.support.v7.widget.RecyclerView$Adapter.setHasStableIds(RecyclerView.java:5535)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPagerAdapter.setHasStableIds(RecyclerViewPagerAdapter.java:57)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPagerAdapter.<init>(RecyclerViewPagerAdapter.java:21)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.ensureRecyclerViewPagerAdapter(RecyclerViewPager.java:495)
                      at com.lsjwzh.widget.recyclerviewpager.RecyclerViewPager.setAdapter(RecyclerViewPager.java:123)
                      at ...targetlist.TargetlistScreenFragment.setupRecyclerView(TargetlistScreenFragment.java:61)

**Comment by emisvx** [comment]
Also having the same problem. I'm currently using Android Annotations to inject the adapter so i can't really control it's lifecycle.

**Comment by KishorAndroid** [comment]
What if we replace ensureRecyclerViewPagerAdapter(...) function 
```
@SuppressWarnings("unchecked")
    @NonNull
    protected RecyclerViewPagerAdapter ensureRecyclerViewPagerAdapter(Adapter adapter) {
        return (adapter instanceof RecyclerViewPagerAdapter)
                ? (RecyclerViewPagerAdapter) adapter
                : new RecyclerViewPagerAdapter(this, adapter);

    }
```
with

```
@SuppressWarnings("unchecked")
    @NonNull
    protected RecyclerViewPagerAdapter ensureRecyclerViewPagerAdapter(Adapter adapter) {
        return new RecyclerViewPagerAdapter(this, adapter);
    }
```

I think it will create new Adapter every time.

**Comment by ncapdevi** [comment]
Getting the same issues when using the RecyclerViewPager as a nested horizontal row within a traditional vertical RecyclerView, when it goes through and rebinds the row, it hits this issue.

**Comment by 4ndro1d** [comment]
Any solutions on this issue?

**Comment by lumyus** [comment]
Facing the same issue when extending a class with recyclerviewpager, that was previously extending a regular recyclerview.
Any updates?

**Comment by lumyus** [comment]
I got a workaround for that did the trick for me.
**Remove** the following line from the class that extends RecyclerViewPager:
`  @Override public void setHasStableIds(boolean hasStableIds) {
      origin.setHasStableIds(hasStableIds);
    }`
Have a good one and thanks @lsjwzh  for the library!
